[package]
name = "problem_sets"
version = "0.1.0"
authors = ["kyle wilcox <wilcox32ahs@gmail.com>"]
edition = "2018"
test = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
